# Generated by Django 5.0.7 on 2024-07-31 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[(True, 'Open'), (False, 'Close')], default=True, max_length=4),
            preserve_default=False,
        ),
    ]
