# Generated by Django 5.0.7 on 2024-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[(True, 'Open'), (False, 'Close')], default='Open', max_length=4),
        ),
    ]
