# Generated by Django 5.0.7 on 2024-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='Open', max_length=10),
        ),
    ]
