# Generated by Django 5.0.7 on 2024-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_chat_description_alter_chat_status_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isDirect',
            field=models.BooleanField(default=False),
        ),
    ]
