# Generated by Django 5.0.7 on 2024-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_chat_isdirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
